services:
  monero:
    image: ghcr.io/rblaine95/monero:latest
    container_name: monero
    restart: unless-stopped
    volumes:
      - /drive2/monero:/opt/bitmonero
    ports:
      # P2P port
      - '18080:18080'
      # Restricted RPC port for wallet connections
      - '18089:18089'
    command:
      - --non-interactive
      - --no-igd
      - --p2p-bind-ip=0.0.0.0
      - --p2p-bind-port=18080
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --confirm-external-bind
      - --enable-dns-blocklist
      - --ban-list=/opt/bitmonero/ban_list.txt
      - --pad-transactions
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:18089/get_height']
      interval: 30s
      timeout: 10s
      retries: 3
