services:
  bitcoin:
    image: bitcoin/bitcoin:29.0
    container_name: bitcoin
    restart: unless-stopped
    init: true
    stop_grace_period: 1m
    ports:
      - '8333:8333'
      - '8332:8332'
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin
    command:
      - -server=1
      - -printtoconsole=1
      - -prune=0 # full node
      - -natpmp=1 # auto-port map on NAT-PMP/PCP routers
      - -rpcbind=0.0.0.0
      - -rpcallowip=172.16.0.0/12 # Docker's internal network range
      - -rpcallowip=127.0.0.1 # Localhost
      - -rpcallowip=192.168.0.0/16 # Most home networks
      - -rpcallowip=100.64.0.0/10 # Tailscale network range
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test:
        [
          'CMD',
          'bitcoin-cli',
          '-datadir=/home/bitcoin/.bitcoin',
          'getblockchaininfo',
        ]
      interval: 30s
      timeout: 10s
      start_period: 600s
      retries: 20

  monero:
    image: ghcr.io/rblaine95/monero:0.18.4.2-1
    container_name: monero
    restart: unless-stopped
    volumes:
      - monero-data:/opt/bitmonero
    ports:
      - '18080:18080'
      - '18089:18089'
    command:
      - --non-interactive
      - --p2p-bind-ip=0.0.0.0
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --confirm-external-bind
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:18089/get_height']
      interval: 30s
      timeout: 10s
      start_period: 600s
      retries: 3
  snowflake:
    image: thetorproject/snowflake-proxy:v2.11.0
    container_name: snowflake
    restart: unless-stopped

  reth:
    image: ghcr.io/paradigmxyz/reth:v1.6.0
    container_name: reth
    restart: unless-stopped
    volumes:
      - reth-data:/data
      - /drive1/ethereum/jwt.hex:/data/jwt.hex:ro
    ports:
      - '30303:30303/tcp' # Ethereum P2P (execution) TCP
      - '30303:30303/udp' # Ethereum P2P (execution) UDP
      - '127.0.0.1:8545:8545' # HTTP JSON-RPC (host-only)
    command:
      - node
      - --chain=mainnet
      - --datadir=/data
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.corsdomain=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/data/jwt.hex
      - --port=30303

  lighthouse:
    image: sigp/lighthouse:v7.1.0 # tip: pin a specific version later
    container_name: lighthouse
    restart: unless-stopped
    depends_on:
      - reth
    volumes:
      - lighthouse-data:/data
      - /drive1/ethereum/jwt.hex:/jwt/jwt.hex:ro
    ports:
      - '9000:9000/tcp' # Ethereum P2P (consensus) TCP
      - '9000:9000/udp' # Ethereum P2P (consensus) UDP
      - '127.0.0.1:5052:5052' # Beacon REST API (host-only)
    command:
      - lighthouse
      - bn
      - --network=mainnet
      - --datadir=/data
      - --execution-endpoint=http://reth:8551
      - --jwt-secrets=/jwt/jwt.hex
      - --checkpoint-sync-url=https://mainnet.checkpoint.sigp.io

volumes:
  bitcoin-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /drive2/bitcoin
  monero-data:
    driver: local
    driver_opts:
      type: none
      device: /drive2/monero
      o: bind
  reth-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /drive1/ethereum/reth
  lighthouse-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /drive1/ethereum/lighthouse
