services:
  bitcoin:
    image: bitcoin/bitcoin:latest
    container_name: bitcoin
    restart: unless-stopped
    init: true
    stop_grace_period: 1m
    ports:
      - '8333:8333'
      - '127.0.0.1:8332:8332' # host-only RPC
    volumes:
      # image expects data at /home/bitcoin/.bitcoin by default
      - /drive2/bitcoin:/home/bitcoin/.bitcoin
    environment:
      # match container file ownership to your host user
      - UID=1000
      - GID=1000
    command:
      - -server=1
      - -printtoconsole=1
      - -prune=0 # full node
      - -natpmp=1 # auto-port map on NAT-PMP/PCP routers

    # Keep Docker logs under control
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

    # Mark container healthy when RPC responds
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'bitcoin-cli -getblockchaininfo >/dev/null 2>&1 || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 20
